<script setup>
import {ref,watch,onBeforeUnmount} from 'vue';
import {createSocialSDK} from '../../sdk/social.mjs';
import {createSocialReader} from '../../sdk/social-read.mjs';
import {publicClient as client,zeroHash} from '../../sdk/chain.mjs';
const props=defineProps(['config','wallet','account','statementId','profileAddress','contextEpoch']),emit=defineEmits(['transaction','open-profile']);
const rows=ref([]),profile=ref(null),busy=ref(false),error=ref(''),notice=ref(''),sort=ref('top'),cursor=ref(0),next=ref(null),total=ref(0),block=ref(''),focus=ref(null),reply=ref(null),text=ref(''),name=ref(''),bio=ref(''),blogTitle=ref(''),blogText=ref(''),editing=ref(null),editTitle=ref(''),editText=ref(''),histories=ref({}),profileVersions=ref([]),profileCursor=ref(0),childCursor=ref(0),childNext=ref(null);
let epoch=0,readSerial=0;
const short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'',own=a=>a?.toLowerCase()===props.account?.toLowerCase();
function adapter(ticket=epoch){if(!props.config?.social)throw Error('Onchain social is not installed yet');return createSocialSDK({client,wallet:props.wallet,address:props.config.social,abi:props.config.abis.AgoraSocial,assertCurrent:()=>{if(ticket!==epoch)throw Error('Wallet or view changed');}});}
async function refresh(){const serial=++readSerial,ticket=epoch,sdk=adapter(ticket),reader=createSocialReader(sdk),blockNumber=(await sdk.snapshot()).number;let p,data;
 if(props.profileAddress)p=await reader.profile(props.profileAddress,{blockNumber});
 if(focus.value){const root=await sdk.post(focus.value,{viewer:props.account,blockNumber}),children=await reader.children(root.id,{cursor:childCursor.value,limit:10,viewer:props.account,blockNumber});data={items:[root,...children.items],nextCursor:null,total:1,blockNumber:String(blockNumber)};if(ticket===epoch)childNext.value=children.nextCursor;}
 else if(props.profileAddress)data=await reader.blogs(props.profileAddress,{cursor:cursor.value,limit:10,viewer:props.account,blockNumber});
 else data=await reader.discussion(props.statementId,{cursor:cursor.value,limit:10,sort:sort.value,viewer:props.account,blockNumber});
 if(ticket!==epoch||serial!==readSerial)return;rows.value=data.items;next.value=data.nextCursor;total.value=data.totalRoots??data.total??0;block.value=data.blockNumber;if(p){profile.value=p;name.value=p.displayName;bio.value=p.bio;}
}
async function run(fn){const ticket=epoch;busy.value=true;error.value='';notice.value='';try{const r=await fn(adapter(ticket));if(ticket!==epoch)return;if(r?.transactionHash){emit('transaction',r);notice.value='Confirmed onchain; earlier versions remain public.';}await refresh();}catch(e){if(ticket===epoch)error.value=e.shortMessage??e.message;}finally{if(ticket===epoch)busy.value=false;}}
function reset(){epoch++;rows.value=[];profile.value=null;cursor.value=0;next.value=null;focus.value=null;reply.value=null;text.value='';name.value='';bio.value='';blogTitle.value='';blogText.value='';editing.value=null;editTitle.value='';editText.value='';histories.value={};profileVersions.value=[];profileCursor.value=0;childCursor.value=0;childNext.value=null;busy.value=false;error.value='';notice.value='';if(props.config?.social)run(async()=>{});}
watch(()=>[props.account,props.wallet,props.statementId,props.profileAddress,props.config?.social,props.contextEpoch],reset,{immediate:true,flush:'sync'});onBeforeUnmount(()=>epoch++);
function publishProfile(){const data={displayName:name.value,bio:bio.value,expectedVersionCount:profile.value.versionCount};return run(sdk=>sdk.publishProfile(data));}
function publishComment(){const body=text.value,parent=reply.value;return run(async sdk=>{const r=await sdk.publishComment(parent?.statementId??props.statementId??zeroHash,body,parent?.id??null);text.value='';reply.value=null;return r;});}
function publishBlog(){const data={title:blogTitle.value,text:blogText.value};return run(async sdk=>{const r=await sdk.publishBlog(data);blogTitle.value='';blogText.value='';return r;});}
function revise(p){const data={title:editTitle.value,text:editText.value};return run(async sdk=>{const r=await sdk.revisePost(p.id,p.version,data);editing.value=null;editText.value='';editTitle.value='';return r;});}
async function loadHistory(p,kind){const ticket=epoch,sdk=adapter(),key=p.id+kind,old=histories.value[key],start=old?.nextCursor??0;try{const page=await(kind==='votes'?sdk.voteHistory(p.id,{cursor:start,limit:5}):kind==='visibility'?sdk.visibilityHistory(p.id,{cursor:start,limit:5}):sdk.revisionHistory(p.id,{cursor:start,limit:5}));if(ticket===epoch)histories.value={...histories.value,[key]:{...page,items:[...(old?.items??[]),...page.items]}};}catch(e){if(ticket===epoch)error.value=e.message;}}
async function loadProfiles(){if(busy.value)return;busy.value=true;const ticket=epoch,sdk=adapter(),items=[];try{for(let i=profileCursor.value;i<Math.min(profileCursor.value+5,profile.value.versionCount);i++)items.push(await sdk.profile(props.profileAddress,{version:i}));if(ticket===epoch){profileVersions.value.push(...items);profileCursor.value+=items.length;}}catch(e){if(ticket===epoch)error.value=e.message;}finally{if(ticket===epoch)busy.value=false;}}
function openThread(p){epoch++;focus.value=p.id;childCursor.value=0;reply.value=null;run(async()=>{});}
function pageTo(n){epoch++;cursor.value=n;focus.value=null;reply.value=null;run(async()=>{});}
</script>
<template><section class="onchain-social">
 <div class="eyebrow">ONCHAIN RESEARCH ARCHIVE · SOLADY SSTORE2</div>
 <p class="muted">Full profiles, posts, replies, votes and every revision are public blockchain data. Publishing requires a wallet transaction and gas. Hiding cannot erase text or replies. Your private shelf and notebook are separate.</p>
 <p v-if="!config?.social">The onchain archive is not installed yet. Legacy offchain records remain an archive, not signed onchain contributions.</p>
 <template v-else>
 <p class="muted">Read directly from chain 31371 · block {{block}} · contract <code>{{short(config.social)}}</code></p><p v-if="error" class="social-error">{{error}}</p><p v-if="notice">{{notice}}</p><p v-if="busy">Waiting for wallet or blockchain…</p>
 <template v-if="profileAddress&&profile">
  <h1>{{profile.displayName}}</h1><code>{{profile.address}}</code><p>{{profile.bio||'No onchain biography yet.'}}</p><p>{{profile.commentCount}} comments/replies · {{profile.blogCount}} blog posts · {{profile.versionCount}} profile versions</p>
  <details v-if="profile.versionCount"><summary>Public profile history</summary><article v-for="p in profileVersions" :key="p.version"><strong>Version {{p.version}} · {{p.displayName}}</strong><p>{{p.bio}}</p><small>{{p.updatedAt}}</small></article><button :disabled="busy||profileCursor>=profile.versionCount" @click="loadProfiles">Load next profile versions</button></details>
  <div v-if="own(profileAddress)" class="panel"><h2>Publish your profile</h2><label>DISPLAY NAME · 192 UTF-8 bytes max<input v-model="name" maxlength="48"></label><label>BIOGRAPHY · 4,000 UTF-8 bytes max<textarea v-model="bio" maxlength="1000"></textarea></label><button class="primary" :disabled="busy||!name.trim()" @click="publishProfile">Publish profile onchain</button></div>
  <div v-if="own(profileAddress)&&!focus" class="panel"><h2>A public research blog</h2><p>Publish explicitly. Private notebook content is never copied automatically. Up to 64 KiB UTF-8 text per article.</p><label>TITLE<input v-model="blogTitle" maxlength="160"></label><label>ARTICLE<textarea v-model="blogText" rows="8"></textarea></label><button class="primary" :disabled="busy||!blogTitle.trim()||!blogText.trim()" @click="publishBlog">Publish blog article onchain</button></div>
 </template>
 <div class="panel-heading"><h2>{{focus?'Thread':profileAddress?'Public blog':'Discuss the mathematics'}}</h2><select v-if="!profileAddress&&!focus" v-model="sort" @change="pageTo(0)" aria-label="Sort onchain comments"><option value="top">Top · highest score</option><option value="new">New · newest roots</option></select></div>
 <p v-if="focus"><button @click="pageTo(cursor)">← Back to root page</button> · Thread #{{focus}} · direct replies {{childCursor+1}}–{{childCursor+Math.max(0,rows.length-1)}}</p><p v-else class="muted">Roots {{total?cursor+1:0}}–{{Math.min(cursor+10,total)}} of {{total}}. Top/New ranks all root headers at this block; replies stay chronological below their parent.</p>
 <div v-if="!profileAddress||reply" class="panel"><p v-if="reply">Reply to #{{reply.id}} <button @click="reply=null">Cancel reply</button></p><label>COMMENT · 10,000 UTF-8 bytes max<textarea v-model="text" rows="4" placeholder="Share an observation, an approach, or a reference…"></textarea></label><button class="primary" :disabled="busy||!account||!text.trim()" @click="publishComment">Publish {{reply?'reply':'comment'}} onchain</button></div>
 <article v-for="p in rows" :key="p.id" class="comment" :style="{marginLeft:`${Math.min(p.depth??0,6)*18}px`}">
  <div class="comment-votes"><button aria-label="Upvote onchain post" :disabled="busy||!account||own(p.author)" :class="{chosen:p.myVote===1}" @click="run(sdk=>sdk.vote(p.id,p.myVote===1?0:1))">▲</button><strong>{{p.score}}</strong><button aria-label="Downvote onchain post" :disabled="busy||!account||own(p.author)" :class="{chosen:p.myVote===-1}" @click="run(sdk=>sdk.vote(p.id,p.myVote===-1?0:-1))">▼</button></div>
  <div class="social-post"><button class="profile-link" @click="emit('open-profile',p.author)">{{p.profile?.displayName??short(p.author)}}</button><time> #{{p.id}} · {{new Date(p.createdAt).toLocaleString()}} · version {{p.version}}</time>
   <p v-if="p.tombstoned">Author hid this post. Exact content and descendants remain available through public version history.</p><template v-else><h3 v-if="p.title">{{p.title}}</h3><p class="social-body">{{p.text}}</p></template><small v-if="p.invalidUtf8">Malformed UTF-8 displayed with replacement characters; exact bytes remain available through SDK reads.</small>
   <div class="button-row"><button :disabled="busy||p.depth>=6" @click="reply=p">Reply</button><small v-if="p.depth>=6">Maximum reply depth 6.</small><button @click="openThread(p)">Open replies / thread</button><button v-if="own(p.author)" :disabled="busy" @click="editing=p.id;editText=p.text;editTitle=p.title">Edit</button><button v-if="own(p.author)" :disabled="busy" @click="run(sdk=>sdk.setTombstone(p.id,!p.tombstoned))">{{p.tombstoned?'Restore post':'Hide own post'}}</button></div>
   <div v-if="editing===p.id"><label v-if="p.kind===1">TITLE<input v-model="editTitle"></label><textarea v-model="editText" rows="5"></textarea><button :disabled="busy" @click="revise(p)">Publish revised version</button><button @click="editing=null;editText='';editTitle=''">Cancel edit</button></div>
   <details v-for="kind in ['revision','votes','visibility']" :key="kind"><summary>Public {{kind}} history {{kind==='revision'?`· ${p.version+1} versions`:''}}</summary><article v-for="(h,i) in histories[p.id+kind]?.items??[]" :key="i"><template v-if="kind==='revision'"><strong>Version {{h.version}} · {{h.title}}</strong><p class="social-body">{{h.text}}</p><small>{{h.at}} · {{h.byteLength}} bytes · {{h.contentHash}}</small></template><p v-else-if="kind==='votes'">{{short(h.voter)}} · {{h.previous}} → {{h.value}} · {{h.createdAt}}</p><p v-else>{{h.tombstoned?'Hidden':'Restored'}} · {{h.createdAt}}</p></article><button :disabled="histories[p.id+kind]?.nextCursor===null" @click="loadHistory(p,kind)">Load next {{kind}} records</button></details>
  </div>
 </article>
 <p v-if="!rows.length" class="muted">No onchain contributions in this view yet.</p>
 <div v-if="!focus" class="button-row"><button :disabled="busy||cursor===0" @click="pageTo(Math.max(0,cursor-10))">Previous root page</button><button :disabled="busy||next===null" @click="pageTo(next)">Next root page</button></div>
 <div v-else class="button-row"><button :disabled="busy||childCursor===0" @click="childCursor=Math.max(0,childCursor-10);run(async()=>{})">Previous replies</button><button :disabled="busy||childNext===null" @click="childCursor=childNext;run(async()=>{})">Next replies</button></div>
 </template>
</section></template>
<style scoped>.social-post{min-width:0;flex:1}.social-body{white-space:pre-wrap;overflow-wrap:anywhere}.social-error{color:#9b2929}.onchain-social details{margin:12px 0}.onchain-social details article{padding:12px;background:#f7f4ee}.onchain-social code,.onchain-social small{overflow-wrap:anywhere}.onchain-social button:disabled{opacity:.45;cursor:not-allowed}</style>
