import test from 'node:test';import assert from 'node:assert/strict';import {newCreation,resumeCreation} from '../src/create-flow.mjs';
const state=()=>newCreation({owner:'alice',registry:'registry',token:'token',title:'goal',funding:20n,fee:2n,registerCall:{method:'register',args:['goal','profile','uri','cert']}});
function fixture(failure){const calls=[],confirmed=new Map();let failed=false;const env={owner:'alice',registry:'registry',assertCurrent(){},event:(_,event)=>({StatementRegistered:{statementId:'statement',creator:'alice'},MarketCreated:{pool:'pool',statementId:'statement',creator:'alice',fee:2n},Approval:{owner:'alice',spender:'pool',value:20n},FPMMFundingAdded:{funder:'alice',amountsAdded:[20n,18n]}}[event]),allowance:async()=>0n,receipt:async hash=>confirmed.get(hash),send:async(address,contract,method,args,{onSubmitted})=>{calls.push(method);const hash='tx-'+method,result={status:'success',transactionHash:hash};if(method===failure&&!failed){failed=true;if(failure==='addFunding'){onSubmitted(hash);confirmed.set(hash,result);}throw Error('Interrupted '+method)}onSubmitted(hash);confirmed.set(hash,result);return result;}};return{env,calls};}
test('pool failure resumes after registration, keeps exact frozen amount and does not register twice',async()=>{const s=state(),f=fixture('createPool');await assert.rejects(resumeCreation(s,f.env));assert.equal(s.statementId,'statement');assert.equal(s.pool,null);await resumeCreation(s,f.env);assert.equal(s.complete,true);assert.equal(f.calls.filter(x=>x==='register').length,1);assert.equal(f.calls.filter(x=>x==='addFunding').length,1);});
test('submitted funding with lost response is resolved by receipt and never sent twice',async()=>{const s=state(),f=fixture('addFunding');await assert.rejects(resumeCreation(s,f.env));assert.equal(s.pending.step,'funding');await resumeCreation(s,f.env);await resumeCreation(s,f.env);assert.equal(s.complete,true);assert.equal(f.calls.filter(x=>x==='addFunding').length,1);});
test('wrong owner/registry and unknown pending receipt never trigger another write',async()=>{const s=state(),f=fixture('addFunding');await assert.rejects(resumeCreation(s,{...f.env,owner:'bob'}));assert.equal(f.calls.length,0);await assert.rejects(resumeCreation(s,f.env));const n=f.calls.length;await assert.rejects(resumeCreation(s,{...f.env,receipt:async()=>{throw Error('Still pending')}}));assert.equal(f.calls.length,n);assert.equal(s.pending.step,'funding');});
test('zero funding creates only a registry entry and an empty pool',async()=>{const s=state();s.funding=0n;const f=fixture();await resumeCreation(s,f.env);assert.deepEqual(f.calls,['register','createPool']);});

test('successful replacement receipt without expected funding event is not accepted',async()=>{const s=state(),f=fixture('addFunding');await assert.rejects(resumeCreation(s,f.env));const prior=f.env.event;f.env.event=(r,name,...args)=>{if(name==='FPMMFundingAdded')throw Error('No funding event');return prior(r,name,...args)};await assert.rejects(resumeCreation(s,f.env),/expected funding/);await assert.rejects(resumeCreation(s,f.env),/expected funding/);assert.equal(s.pending.step,'funding');assert.equal(s.receipts.funding,undefined);assert.equal(s.complete,false);assert.equal(f.calls.filter(x=>x==='addFunding').length,1);});
