import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {sha256} from 'viem';import {base64} from '@scure/base';
import {verifyGenericCertificate} from '../server/generic-certificates.mjs';
const directory=new URL('../proof/additional-profiles/perf05/',import.meta.url),read=p=>fs.readFileSync(new URL(p,directory));
const profile={...JSON.parse(read('profile.json')),fixtures:{},verifierParameters:'0x73c457ba541936f0d907daf0c7253a39a9c5c427c225ba7709e44702d3c6eedc',selector:'0x73c457ba'},bridge='0x'+'12'.repeat(20),original='0x'+'34'.repeat(20),registry='0x'+'56'.repeat(20),manifestHash='0x'+'78'.repeat(32);
const profiles=[{trustedProfile:profile,foundationBytes:new Uint8Array(read('fixtures/foundation.ndjson')),bridge,manifestHash,name:'perf05'}];
const wrap=(file='registration.json')=>{const artifact=JSON.parse(read(file)),goal=read(`fixtures/${file.startsWith('false')?'false':'true'}-goal.ndjson`);return{format:'oncm-external-certificate-bundle-v1',artifact,goalExport:{base64:base64.encode(goal),sha256:sha256(goal).slice(2),bytes:goal.length},metadata:{title:'A generic goal'},source:{text:'Different text, explicitly not a verified rendering',sha256:sha256(new TextEncoder().encode('Different text, explicitly not a verified rendering')).slice(2)}};};
function environment({enabled=true,rejectOriginal=false,rejectBridge=false,profileState}={}){const calls=[];return{profiles,registry,registryAbi:[],bridgeAbi:[],client:{readContract:async request=>{calls.push(request);if(request.functionName==='profiles')return profileState??[bridge,manifestHash,enabled];if(request.functionName==='imageId')return profile.imageId;if(request.functionName==='profileId')return profile.profileId;if(request.functionName==='verifier')return original;if(request.address===original){if(rejectOriginal)throw Error('Original pairing rejected');return undefined;}return!rejectBridge;}},calls};}
test('generic registration without fixtures explicitly calls original pairing then bridge; source remains unverified',async()=>{const env=environment();const result=await verifyGenericCertificate(wrap(),{...env,blockNumber:99n});assert.equal(result.verificationBlock,'99');assert.ok(env.calls.every(c=>c.blockNumber===99n));assert.equal(result.generic,true);assert.equal(result.enabled,true);assert.equal(result.sourceGoalRelation,'not-verified');assert.equal(result.cryptographicStatus,'verified-original-evm-and-bridge');assert.deepEqual(env.calls.map(r=>r.functionName),['profiles','imageId','profileId','verifier','verify','verifyGoal']);assert.equal(env.calls[4].address,original);});
test('JSON evmVerified flag does not bypass failed original verifier or false bridge',async()=>{const b=wrap();b.artifact.evmVerified=true;await assert.rejects(verifyGenericCertificate(b,environment({rejectOriginal:true})),/pairing rejected/);await assert.rejects(verifyGenericCertificate(b,environment({rejectBridge:true})),/bridge rejected/);});
test('disabled admission is reported; an existing matching open mathematical statement still verifies settlement',async()=>{const env=environment({enabled:false});assert.equal((await verifyGenericCertificate(wrap(),env)).enabled,false);const proof=wrap('true-proof.json');const statement={id:'0x'+'99'.repeat(32),goalHash:proof.artifact.goalHash,profileId:profile.profileId,kind:0,outcome:0};assert.equal((await verifyGenericCertificate(proof,{...env,statement})).outcome,1);});
test('settlement rejects no statement, changed goal/profile, derived or already resolved target before crypto',async()=>{const b=wrap('false-refutation.json'),statement={id:'0x'+'99'.repeat(32),goalHash:b.artifact.goalHash,profileId:profile.profileId,kind:0,outcome:0};await assert.rejects(verifyGenericCertificate(b,environment()),/Select/);for(const patch of [{goalHash:'0x'+'aa'.repeat(32)},{profileId:'0x'+'bb'.repeat(32)},{kind:1},{outcome:2}]){const env=environment();await assert.rejects(verifyGenericCertificate(b,{...env,statement:{...statement,...patch}}),/open mathematical/);assert.equal(env.calls.length,0);}});
test('installed profile must match trusted bridge and descriptor pin',async()=>{for(const state of [['0x'+'00'.repeat(20),manifestHash,true],[bridge,'0x'+'ff'.repeat(32),true]])await assert.rejects(verifyGenericCertificate(wrap(),environment({profileState:state})),/not installed/);});
