import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{decodeFunctionData,encodeFunctionData}from'viem';import{governanceTreasuryCall,governanceShareDraft,sharePercent,allocationDraftReview,readTreasury}from'../sdk/treasury.mjs';import{composeGovernanceCall,reviewGovernanceAction}from'../server/governance-actions.mjs';
const a=n=>'0x'+n.toString(16).padStart(40,'0'),hash='0x'+'12'.repeat(32),manifest={registry:a(1),allocation:a(2),timelock:a(3),safe:a(4),token:a(5)},abis=Object.fromEntries(['AgoraRegistry','AllocationController','TrueToken'].map(n=>[n,JSON.parse(fs.readFileSync(new URL('../artifacts/'+n+'.json',import.meta.url))).abi]));
const block={number:97n,timestamp:100n},proposal={baseVersion:2n,expiresAt:200n,executed:false,payees:[manifest.timelock],shares:[150000n]};
function review(call,overrides={}){const seen=[];const values={proposal,currentEpoch:2n,currentShare:200000n,balanceOf:10n**18n,...overrides};return{seen,promise:reviewGovernanceAction({...call,manifest,abis,block,read:async(address,name,fn,args,at)=>{seen.push({address,fn,args,at});return values[fn];}})};}
test('Treasury uses exact Timelock beneficiary; consent is typed controller calldata, never Safe/EOA approval',async()=>{
 const call=governanceTreasuryCall({kind:'allocation-consent',proposalId:'7',approve:true},manifest,abis);assert.equal(call.target,manifest.allocation);assert.equal(call.action.executor,manifest.timelock);assert.deepEqual(decodeFunctionData({abi:abis.AllocationController,data:call.data}).args,[7n,true]);const f=review(call),context=await f.promise;assert.equal(context.baseVersion,'2');assert.equal(context.newShare,'150000');assert(f.seen.every(c=>c.at.blockNumber===97n));assert.deepEqual(f.seen.find(c=>c.fn==='currentShare').args,[manifest.timelock]);
 await assert.rejects(review({...call,target:manifest.safe}).promise,/binding/);await assert.rejects(review({...call,action:{...call.action,executor:manifest.safe}}).promise,/binding/);
});
test('Stale, expired, applied and nondecreasing outer proposals cannot become active treasury approvals',async()=>{
 const call=governanceTreasuryCall({kind:'allocation-consent',proposalId:'7',approve:false},manifest,abis);assert.deepEqual(decodeFunctionData({abi:abis.AllocationController,data:call.data}).args,[7n,false]);
 for(const changes of[{currentEpoch:3n},{proposal:{...proposal,expiresAt:99n}},{proposal:{...proposal,executed:true}},{currentShare:150000n}])await assert.rejects(review(call,changes).promise,/stale|expired|decrease/);
 await assert.rejects(review({...call,action:{...call.action,baseVersion:'1'}}).promise,/epoch/);
});
test('Transfer exact decimal/base-unit binding and current treasury balance are checked',async()=>{
 const call=governanceTreasuryCall({kind:'treasury-transfer',recipient:a(8),amount:'0.123456789012345678'},manifest,abis);assert.equal(call.target,manifest.token);assert.deepEqual(decodeFunctionData({abi:abis.TrueToken,data:call.data}).args,[a(8),123456789012345678n]);await review(call).promise;await assert.rejects(review(call,{balanceOf:0n}).promise,/balance/);
 for(const amount of['0','1e2','-1','0.0000000000000000001'])assert.throws(()=>governanceTreasuryCall({kind:'treasury-transfer',recipient:a(8),amount},manifest,abis));assert.throws(()=>governanceTreasuryCall({kind:'treasury-transfer',recipient:manifest.timelock,amount:'1'},manifest,abis));
});
test('Current epoch97 Math20/Reviewer40/Curator40 drafts16/32/32+Timelock20 and shows ALL losers',()=>{
 const current={epoch:2,recipients:[a(6),a(7),a(8)],shares:[200000n,400000n,400000n]},rows=governanceShareDraft(current,manifest.timelock,'20');const percentages=Object.fromEntries(rows.map(r=>[r.address,sharePercent(r.share)]));assert.deepEqual(percentages,{[manifest.timelock]:'20',[a(6)]:'16',[a(7)]:'32',[a(8)]:'32'});const text=rows.map(r=>`${r.address} ${sharePercent(r.share)}`).join('\n'),r=allocationDraftReview(text,current);assert.equal(r.valid,true);assert.equal(r.baseEpoch,'2');assert.equal(r.rows.filter(r=>r.loses).length,3);assert.equal(r.rows.find(r=>r.address===manifest.timelock).previous,0n);assert.equal(allocationDraftReview(text+'\n'+a(6)+' 1',current).valid,false);
 const uneven=governanceShareDraft({recipients:[a(6),a(7),a(8)],shares:[333333n,333333n,333334n]},manifest.timelock,'20');assert.equal(uneven.reduce((n,r)=>n+r.share,0n),1000000n);
});
test('Existing profile/operator/disable calldata and legacy immutable proposals remain supported',async()=>{
 for(const kind of['profile','operator','disable']){const b={kind,profileId:hash,verifier:a(9),manifestHash:hash,enabled:false},call=composeGovernanceCall(b,manifest,abis),fn={profile:'configureProfile',operator:'configureOperator',disable:'setProfileEnabled'}[kind];assert.equal(call.target,manifest.registry);assert.equal(call.data,encodeFunctionData({abi:abis.AgoraRegistry,functionName:fn,args:kind==='disable'?[hash,false]:[hash,a(9),hash]}));}assert.equal(await reviewGovernanceAction({}),null);assert.throws(()=>composeGovernanceCall({kind:'arbitrary-call'},manifest,abis),/Unknown/);
});
test('Treasury epoch claim reads always name Timelock and never the initiating account',async()=>{
 const calls=[];const result=await readTreasury({config:manifest,blockNumber:97n,read:async(address,name,fn,args,at)=>{calls.push({fn,args,at});return fn==='splits'?a(20):fn==='currentEpoch'?0n:5n;}});assert.equal(result.address,manifest.timelock);assert.equal(result.epochs[0].claimable,5n);assert(calls.every(c=>c.at.blockNumber===97n));assert.deepEqual(calls.find(c=>c.fn==='releasable').args,[manifest.token,manifest.timelock]);
});
