import test from 'node:test';import assert from 'node:assert/strict';
import {getAddress,ZeroAddress,Interface} from 'ethers';
import {PUBLIC_DEV_ADDRESSES,publicControlViolations,findPilotCutover,createPublicReadinessVerifier} from '../server/public-write-readiness.mjs';
import {preparePilotFeeMigration,preparePilotGasFunding} from '../scripts/public-pilot-migration-plan.mjs';
const owner=getAddress('0x4b5d2b35f36a3ac018d5c9a9c394fadae667fb2f'),unit='1000000000000000000',addr=n=>getAddress('0x'+n.toString(16).padStart(40,'0'));
const a={Membership:addr(1),Governor:addr(2),Timelock:addr(3),TrueToken:addr(4),StatementRegistry:addr(5),AllocationController:addr(6),Vault:addr(7),Authorizer:addr(8),ProtocolFeeController:addr(9)};
function valid(){return {chainId:31373,protocolVersion:'2',owner,addresses:a,runtimeVerified:true,block:{number:100,hash:'hash100',timestamp:1000},memberSupply:unit,members:[...PUBLIC_DEV_ADDRESSES.map(address=>({address,balance:'0',votes:'0',delegate:ZeroAddress})),{address:owner,balance:unit,votes:unit,delegate:owner}],owners:{Membership:a.Timelock,TrueToken:a.Timelock},governor:{token:a.Membership,timelock:a.Timelock},timelock:{roles:{DEFAULT_ADMIN_ROLE:[a.Timelock],PROPOSER_ROLE:[a.Governor],CANCELLER_ROLE:[a.Governor],EXECUTOR_ROLE:[ZeroAddress]}},bindings:{vaultAuthorizer:a.Authorizer,vaultController:a.ProtocolFeeController,expected:{},actual:{}},beneficiaries:{recipients:[owner,a.Timelock],weights:['8500','1500']},cutoverBlock:90,cutover:{ownerAdded:owner,burnedPublicMembers:PUBLIC_DEV_ADDRESSES.slice(0,4)},proposals:[]};}
test('exact initial handoff passes; real future members are allowed by continuing gate',()=>{const s=valid();assert.deepEqual(publicControlViolations(s,{initial:true}),[]);s.members.push({address:addr(50),balance:unit,votes:unit,delegate:addr(50)});s.memberSupply=String(2n*BigInt(unit));assert.deepEqual(publicControlViolations(s),[]);assert.ok(publicControlViolations(s,{initial:true}).length);});
test('legitimate future owner removal does not brick governance',()=>{const s=valid();Object.assign(s.members.at(-1),{balance:'0',votes:'0'});s.members.push({address:addr(50),balance:unit,votes:unit,delegate:addr(50)});assert.deepEqual(publicControlViolations(s),[]);});
test('zero balance with residual public dev votes remains blocked',()=>{const s=valid();s.members[0].votes=unit;assert.match(publicControlViolations(s).join(';'),/Residual public dev/);});
test('revocation does not erase pre-cutover queued proposal authority',()=>{const s=valid();s.proposals=[{id:'old',snapshot:'89',state:5,stateName:'Queued'}];assert.match(publicControlViolations(s).join(';'),/Pre-cutover/);s.proposals[0].snapshot='91';assert.deepEqual(publicControlViolations(s),[]);});
test('missing cutover, extra role, and dev fee beneficiary all fail closed',()=>{for(const mutate of[s=>s.cutover=null,s=>s.timelock.roles.CANCELLER_ROLE.push(PUBLIC_DEV_ADDRESSES[0]),s=>s.beneficiaries.recipients.push(PUBLIC_DEV_ADDRESSES[0])]){const s=valid();mutate(s);assert.ok(publicControlViolations(s).length);}});
test('cutover proves one atomic mint/four burns and stays fixed after later owner changes',()=>{const transfers=PUBLIC_DEV_ADDRESSES.slice(0,4).map(to=>({from:ZeroAddress,to,value:unit,blockNumber:1,transactionHash:'genesis'}));transfers.push({from:ZeroAddress,to:owner,value:unit,blockNumber:90,transactionHash:'handoff'},...PUBLIC_DEV_ADDRESSES.slice(0,4).map(from=>({from,to:ZeroAddress,value:unit,blockNumber:90,transactionHash:'handoff'})),{from:owner,to:ZeroAddress,value:unit,blockNumber:120,transactionHash:'later'});assert.equal(findPilotCutover(transfers,owner).blockNumber,90);transfers[5].transactionHash='separate';assert.equal(findPilotCutover(transfers,owner),null);});
function rig(){let number=100,hash='hash100',chain='0x7a8d',changed=false,full=0,time=0,bad=false;const provider={send:async(method,args)=>method==='eth_chainId'?chain:{number:'0x'+number.toString(16),hash:args[0]==='latest'?hash:(Number(BigInt(args[0]))===100?'hash100':hash),timestamp:'0x3e8'},getLogs:async()=>changed?[{}]:[]};const input={provider,owner,config:{protocolVersion:'2',addresses:a,chainInstance:{id:'test'},monetaryPolicy:{runtimeHashes:{}}}};const verifier=createPublicReadinessVerifier({now:()=>time,fullAudit:async()=>{full++;await Promise.resolve();const s=valid();s.block={number,hash,timestamp:1000};if(bad)s.members[0].votes=unit;s.violations=publicControlViolations(s);s.ready=!s.violations.length;return s;}});return {input,verifier,get full(){return full;},head(n){number=n;hash='hash'+n;},event(){changed=true;},bad(){bad=true;},time(t){time=t;},wrongChain(){chain='0x1';}};}
test('concurrent requests coalesce; unchanged authority across blocks avoids full audit',async()=>{const r=rig();await Promise.all([r.verifier(r.input),r.verifier(r.input)]);assert.equal(r.full,1);r.head(101);const s=await r.verifier(r.input);assert.equal(r.full,1);assert.equal(s.block.number,100);assert.equal(s.checkedBlock.number,101);assert.equal(s.auditMode,'event-validated');});
test('a new authority event invalidates cache immediately and fails closed',async()=>{const r=rig();await r.verifier(r.input);r.head(101);r.event();r.bad();await assert.rejects(r.verifier(r.input),/Residual public dev/);assert.equal(r.full,2);});
test('full audit TTL and actual upstream chain are checked',async()=>{const r=rig();await r.verifier(r.input);r.time(60001);await r.verifier(r.input);assert.equal(r.full,2);r.wrongChain();await assert.rejects(r.verifier(r.input),/chain changed/);});
test('descriptor changes invalidate even on the same provider/block',async()=>{const r=rig();await r.verifier(r.input);r.input.config.chainInstance.id='changed';await r.verifier(r.input);assert.equal(r.full,2);});
test('fee migration has exact sorted85/15 rows and only the two decreasing EOA consents',()=>{const plan={owner,observed:{addresses:a,chainInstance:'instance',block:{number:563}},preserved:{allocation:{controller:a.AllocationController,epoch:'1',recipients:[PUBLIC_DEV_ADDRESSES[1],a.Timelock,PUBLIC_DEV_ADDRESSES[0]],weights:['4000','1500','4500']}},balances:[{address:PUBLIC_DEV_ADDRESSES[0],nativeWei:String(1000n*10n**18n)}]};const fee=preparePilotFeeMigration(plan,0n),abi=new Interface(['function propose(address[],uint256[])','function setConsent(uint256,bool)','function applyAllocation(uint256)']);const decoded=abi.decodeFunctionData('propose',fee.transactions[0].calldata);assert.equal(decoded[1].reduce((n,x)=>n+x,0n),10000n);assert.deepEqual(fee.transactions.filter(x=>x.step==='consent').map(x=>x.from),[PUBLIC_DEV_ADDRESSES[1],PUBLIC_DEV_ADDRESSES[0]]);assert.equal(fee.transactions.length,4);assert.equal(preparePilotGasFunding(plan).value,'100000000000000000000');});
